# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QMovie
from PyQt6.QtWidgets import QMessageBox
import os

os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 800)
        # MainWindow.setMinimumSize(QtCore.QSize(482, 1900))
        # MainWindow.setMaximumSize(QtCore.QSize(482, 518))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(1000, 450))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(462, 1940))
        sidelabel = QMovie("Project Name.gif")
        sidelabel.setFormat(b"gif")
        sidelabel.setScaledSize(QSize(462, 750))
        self.label.setMovie(sidelabel)
        sidelabel.start()
        self.label.setStyleSheet("border-image:url();\n"
"width:50%;\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        # self.label.setPixmap(QtGui.QPixmap("pexels-pixabay-268533.jpg"))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_5.setMinimumSize(QtCore.QSize(232, 120))
        self.label_5.setMaximumSize(QtCore.QSize(232, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_7.setMaximumSize(QtCore.QSize(150, 150))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_4.setMinimumSize(QtCore.QSize(200, 100))
        self.label_4.setMaximumSize(QtCore.QSize(200, 100))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("PUSH-logos.jpg"))
        self.label_4.setMinimumSize(150,150)
        # logo = QMovie("Vanilla-1s-201px.gif")
        # logo.setFormat(b"gif")
        # logo.setScaledSize(QSize(150,150))
        # self.label_4.setMovie(logo)
        # logo.start()
        self.label_4.setObjectName("label_4")
        # self.label_4.setStyleSheet("background-color:rgb(140,138,113)")
        self.horizontalLayout_7.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_7, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_4)
        self.lineEdit.setMinimumSize(QtCore.QSize(256, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(256, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.widget_4, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(256,25))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(256, 25))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout.addWidget(self.widget_5, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.widget_6)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Close).clicked.connect(self.closeEvent)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Save).clicked.connect(self.LoginEvent)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Save).setText("Login")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Save).setStyleSheet("background-image: url();\n"
                                                                                            "background-color: rgb(74,159,188);\n"
                                                                                            "padding: 5px 18px 5px 18px;\n"
                                                                                            "border-radius: 5px;")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Close).setStyleSheet("background-image: url();\n"
                                                                                            "background-color: rgb(138, 136, 132);\n"
                                                                                            "padding: 5px 18px 5px 18px;\n"
                                                                                            "border-radius: 5px;")
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_6.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_6.setSpacing(0)
        # self.horizontalLayout_6.setStretch(5,5)
        self.verticalLayout.addWidget(self.widget_6, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Username :"))
        self.label_3.setText(_translate("MainWindow", "Password    : "))

    def closeEvent(self):
        sys.exit(0)

    def LoginEvent(self):
        username = self.lineEdit.text()
        password = self.lineEdit_2.text()

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setWindowTitle("Login")
        msg.setText("You are login with \n Username:"+str(username))
        msg.exec()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
